---
- hosts: all
  tasks:
  - name: Get current site version
    connection: local
    include_vars:
      file: "../package.json"
      name: package_json
  - set_fact: package="{{ package_json }}"
  - name: Deploy Nginx configuration files
    become: yes
    copy:
      src: "{{ item }}"
      dest: "{{ nginx_sites_dir }}"
      owner: "root"
      group: "root"
    with_fileglob:
      - ../etc/nginx/sites-available/{{ nginx_conf_glob }}
  - name: Create site deployment directory
    become: yes
    file:
      path: "{{ deploy_root }}"
      state: directory
      owner: "{{ deploy_owner }}"
      group: "{{ deploy_group }}"
  - name: Deploy site
    become: yes
    unarchive:
      src: ../dist/{{ package.name }}-{{ package.version}}.tar.gz
      dest: "{{ deploy_root }}"
      owner: "{{ deploy_owner }}"
      group: "{{ deploy_group }}"
